/* Generated by AN DISI Unibo */ 
package it.unibo.parkclientservice

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Parkclientservice ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("parkclientservice STARTS")
						updateResourceRep( "parkclientservice STARTS"  
						)
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						println("parkclientservice waiting ...")
						updateResourceRep( "parkclientservice waiting ..."  
						)
					}
					 transition(edgeName="t04",targetState="handleEnterRequest",cond=whenRequest("reqenter"))
					transition(edgeName="t05",targetState="handleOutRequest",cond=whenRequest("reqexit"))
				}	 
				state("handleEnterRequest") { //this:State
					action { //it:State
						println("parkclientservice reply to reqenter")
						updateResourceRep( "parkclientservice reply to reqenter"  
						)
						println("$name in ${currentState.stateName} | $currentMsg")
						if(  utils.ParkingAreaKb2.indoorfree && !utils.ParkingAreaKb2.trolleyStopped  
						 ){ 
										var SLOTNUM = 0
										var i
										for(i = 0; i <= 5 && SLOTNUM == 0; i++) {
											if(utils.ParkingAreaKb2.slotStateFree[i] == true) {
												SLOTNUM = i + 1
												utils.ParkingAreaKb2.slotStateFree[i] == false
											}
										}
						println("parkclientservice reply enter($SLOTNUM)")
						updateResourceRep( "parkclientservice reply enter($SLOTNUM)"  
						)
						answer("reqenter", "enter", "enter($SLOTNUM)"   )  
						if(  SLOTNUM == 0  
						 ){forward("goToWork", "goToWork(enter(0))" ,"parkclientservice" ) 
						}
						}
						else
						 {println("parkclientservice reply enter($SLOTNUM)")
						 updateResourceRep( "parkclientservice reply enter($SLOTNUM)"  
						 )
						 answer("reqenter", "enter", "enter(0)"   )  
						 forward("goToWork", "goToWork(enter(0))" ,"parkclientservice" ) 
						 }
					}
					 transition(edgeName="t06",targetState="work",cond=whenDispatch("goToWork"))
					transition(edgeName="t07",targetState="enterthecar",cond=whenRequest("carenter"))
				}	 
				state("enterthecar") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("parkingmanagerservice reply to enterthecar")
						if( checkMsgContent( Term.createTerm("carenter(SLOTNUM)"), Term.createTerm("carenter(SLOT)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var SLOTNUM = payloadArg(0).toInt()  
								forward("moveToPark", "moveToPark($SLOTNUM)" ,"trolley" ) 
								answer("carenter", "receipt", "receipt($SLOTNUM)"   )  
								println("parkingmanagerservice moves the car to SLOTNUM = $SLOTNUM ")
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("handleOutRequest") { //this:State
					action { //it:State
						println("parkingmanagerservice reply to reqexit")
						if( checkMsgContent( Term.createTerm("reqexit(TOKENID)"), Term.createTerm("reqexit(TOKENID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var CARSLOTNUM = payloadArg(0).toInt()  
								if(  TOKENID >= 1 && TOKENID <= 6 && !utils.ParkingAreaKb2.slotStateFree[TOKENID - 1]  
								 ){forward("moveToOut", "moveToOut($CARSLOTNUM)" ,"trolley" ) 
								}
								else
								 { CARSLOTNUM = 0  
								 }
								answer("reqexit", "exit", "exit($CARSLOTNUM)"   )  
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
}
