/* Generated by AN DISI Unibo */ 
package it.unibo.outdoorparkingservicegui

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Outdoorparkingservicegui ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("outdoorparkingservicegui STARTS")
						updateResourceRep( "outdoorparkingservicegui STARTS"  
						)
					}
					 transition( edgeName="goto",targetState="requestToExit", cond=doswitch() )
				}	 
				state("requestToExit") { //this:State
					action { //it:State
						println("outdoorparkingservicegui requestToExit")
						updateResourceRep( "outdoorparkingservicegui requestToExit"  
						)
						request("reqexit", "reqexit(TOKENID)" ,"parkclientservice" )  
					}
					 transition(edgeName="t03",targetState="afterreceipt",cond=whenReply("exit"))
				}	 
				state("afterreceipt") { //this:State
					action { //it:State
						println("outdoorparkingservicegui leaves")
						updateResourceRep( "outdoorparkingservicegui leaves"  
						)
					}
				}	 
			}
		}
}
