/* Generated by AN DISI Unibo */ 
package it.unibo.managerservice

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Managerservice ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("managerservice STARTS")
						updateResourceRep( "managerservice STARTS"  
						)
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						println("managerservice waiting ...")
						updateResourceRep( "managerservice waiting ..."  
						)
					}
					 transition(edgeName="t011",targetState="toggleTrolleyState",cond=whenDispatch("toggleState"))
				}	 
				state("toggleTrolleyState") { //this:State
					action { //it:State
						if(  ParkingAreaKb.trolleyStopped  
						 ){ ParkingAreaKb.trolleyStopped = false  
						println("managerservice emit resume")
						updateResourceRep( "managerservice emit resume"  
						)
						forward("resume", "resume(X)" ,"trolley" ) 
						}
						else
						 { ParkingAreaKb.trolleyStopped = true  
						 println("managerservice emit stop")
						 updateResourceRep( "managerservice emit stop"  
						 )
						 forward("stop", "stop(X)" ,"trolley" ) 
						 }
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
}
