/* Generated by AN DISI Unibo */ 
package it.unibo.clientservice

import it.unibo.kactor.*
import alice.tuprolog.*
import it.unibo.sembrava_qualcuno.model.Message
import it.unibo.sembrava_qualcuno.sprint3.ParkingAreaKb
import it.unibo.utils.it.unibo.sembrava_qualcuno.sonar.CoapSonar
import it.unibo.utils.it.unibo.sembrava_qualcuno.sonar.SonarController
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import org.eclipse.californium.core.CoapClient

class Clientservice ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
			
				val weightSensor : it.unibo.sembrava_qualcuno.weightsensor.WeightSensorInterface = it.unibo.sembrava_qualcuno.weightsensor.CoapWeightSensor("coap://localhost:8025/weightSensor")	
		        val sonarController = SonarController(CoapSonar("coap://localhost:8026/sonar"))
		        val trolleyResource : org.eclipse.californium.core.CoapClient = CoapClient("coap://localhost:8024/ctxtrolley/trolley")
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("clientservice STARTS")
						updateResourceRep( "clientservice STARTS"  
						)
						  
									if(java.io.File("ServiceState.bin").exists()) {
										val inps = java.io.ObjectInputStream(java.io.FileInputStream("ServiceState.bin"))
										ParkingAreaKb.slot = inps.readObject() as MutableMap<Int, String>
									}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						println("clientservice waiting ...")
						updateResourceRep( "clientservice waiting ..."  
						)
					}
					 transition(edgeName="t00",targetState="handleEnterRequest",cond=whenRequest("reqenter"))
					transition(edgeName="t01",targetState="handleOutRequest",cond=whenRequest("reqexit"))
				}	 
				state("handleEnterRequest") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("clientservice reply to reqenter")
						updateResourceRep( "clientservice reply to reqenter"  
						)
						 
						            lateinit var message : Message
						            var SLOTNUM = 0  
						if(  weightSensor.getWeight() == 0  
						 ){if(  trolleyResource.get().getResponseText() != ("trolley STOPPED")  
						 ){
							                for(i in 1..6) {
							                    if(ParkingAreaKb.slot.get(i).equals("")) {
							                        SLOTNUM = i
							                        break
							                    }
							                }
						if(  SLOTNUM == 0  
						 ){forward("goToWork", "goToWork(enter($SLOTNUM))" ,"clientservice" ) 
						}
						 message = Message(0, "$SLOTNUM")
						}
						else
						 {forward("goToWork", "goToWork(enter($SLOTNUM))" ,"clientservice" ) 
						  message = Message(7, "The trolley is stopped")  
						 }
						}
						else
						 {forward("goToWork", "goToWork(enter($SLOTNUM))" ,"clientservice" ) 
						  message = Message(1, "The indoor area is engaged")  
						 }
						println("clientservice reply enter($SLOTNUM)")
						updateResourceRep( "$SLOTNUM"  
						)
						 val RESPONSE = Json.encodeToString(message)
						answer("reqenter", "enter", "$RESPONSE"   )  
						stateTimer = TimerActor("timer_handleEnterRequest", 
							scope, context!!, "local_tout_clientservice_handleEnterRequest", 60000.toLong() )
					}
					 transition(edgeName="t02",targetState="work",cond=whenTimeout("local_tout_clientservice_handleEnterRequest"))   
					transition(edgeName="t03",targetState="work",cond=whenDispatch("goToWork"))
					transition(edgeName="t04",targetState="enterthecar",cond=whenRequest("carenter"))
				}	 
				state("enterthecar") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("clientservice reply to carenter")
						updateResourceRep( "parkingclientservice reply to carenter"  
						)
						if( checkMsgContent( Term.createTerm("carenter(SLOTNUM)"), Term.createTerm("carenter(SLOTNUM)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var SLOTNUM = payloadArg(0).toInt()  
								if(  SLOTNUM in 1..6 && ParkingAreaKb.slot.get(SLOTNUM).equals("")  
								 ){if(  weightSensor.getWeight() > 0  
								 ){
														val sdf = java.text.SimpleDateFormat("ddMMyyyyhhmmss")
														val currentDate = sdf.format(java.util.Date())	
														val TOKENID = "$SLOTNUM$currentDate"
								 val RESPONSE = Json.encodeToString(Message(0, "$TOKENID"))  
								answer("carenter", "receipt", "$RESPONSE"   )  
								forward("moveToInOutdoor", "moveToInOutdoor(indoor)" ,"trolley" ) 
								delay(2000) 
								println("clientservice moves the car to SLOTNUM = $SLOTNUM")
								updateResourceRep( "parkingclientservice moves the car to SLOTNUM = $SLOTNUM"  
								)
								forward("moveToPark", "moveToPark($SLOTNUM)" ,"trolley" ) 
								 ParkingAreaKb.slot.set(SLOTNUM, "$TOKENID")  
								
														val os = java.io.ObjectOutputStream( java.io.FileOutputStream("ServiceState.bin") )
														os.writeObject(ParkingAreaKb.slot)
														os.flush()
														os.close()
								forward("goToWork", "goToWork(enter($SLOTNUM))" ,"clientservice" ) 
								}
								else
								 { val RESPONSE = Json.encodeToString(Message(2, "The indoor area is free"))  
								 answer("carenter", "receipt", "$RESPONSE"   )  
								 }
								}
								else
								 { val RESPONSE = Json.encodeToString(Message(3, "Invalid parking slot number"))  
								 answer("carenter", "receipt", "$RESPONSE"   )  
								 }
								println("clientservice reply")
								updateResourceRep( "clientservice reply"  
								)
						}
						stateTimer = TimerActor("timer_enterthecar", 
							scope, context!!, "local_tout_clientservice_enterthecar", 60000.toLong() )
					}
					 transition(edgeName="t05",targetState="work",cond=whenTimeout("local_tout_clientservice_enterthecar"))   
					transition(edgeName="t06",targetState="work",cond=whenDispatch("goToWork"))
					transition(edgeName="t07",targetState="enterthecar",cond=whenRequest("carenter"))
				}	 
				state("handleOutRequest") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("clientservice reply to reqexit")
						updateResourceRep( "parkingclientservice reply to reqexit"  
						)
						if( checkMsgContent( Term.createTerm("reqexit(TOKENID)"), Term.createTerm("reqexit(TOKENID)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var TOKENID = payloadArg(0)  
								if(  sonarController.isOutdoorFree()  
								 ){if(  trolleyResource.get().getResponseText() != ("trolley STOPPED")  
								 ){ 
														var SLOTNUM = 0
														ParkingAreaKb.slot.forEach { (k, v) -> 
															if(v == TOKENID)
																SLOTNUM = k
														}
								if(  SLOTNUM != 0  
								 ){ val RESPONSE = Json.encodeToString(Message(0, "Success"))  
								answer("reqexit", "exit", "$RESPONSE"   )  
								forward("moveToPark", "moveToPark($SLOTNUM)" ,"trolley" ) 
								delay(2000) 
								println("clientservice moves the car from SLOTNUM = $SLOTNUM")
								updateResourceRep( "clientservice moves the car from SLOTNUM = $SLOTNUM"  
								)
								forward("moveToInOutdoor", "moveToInOutdoor(outdoor)" ,"trolley" ) 
								 ParkingAreaKb.slot.set(SLOTNUM, "")  
								
															val os = java.io.ObjectOutputStream( java.io.FileOutputStream("ServiceState.bin") )
															os.writeObject(ParkingAreaKb.slot)
															os.flush()
															os.close()
								}
								else
								 { val RESPONSE = Json.encodeToString(Message(4, "Invalid tokenid"))  
								 answer("reqexit", "exit", "$RESPONSE"   )  
								 }
								}
								else
								 { val RESPONSE = Json.encodeToString(Message(6, "The trolley is stopped"))  
								 answer("reqexit", "exit", "$RESPONSE"   )  
								 }
								}
								else
								 { val RESPONSE = Json.encodeToString(Message(5, "The outdoor area is engaged"))  
								 answer("reqexit", "exit", "$RESPONSE"   )  
								 }
								println("clientservice reply")
								updateResourceRep( "clientservice reply"  
								)
						}
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
			}
		}
}
