/* Generated by AN DISI Unibo */ 
package it.unibo.indoorparkingservicegui

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Indoorparkingservicegui ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		 var SLOTNUM = 0  
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("indoorparkingservicegui STARTS")
						updateResourceRep( "indoorparkingservicegui STARTS"  
						)
					}
					 transition( edgeName="goto",targetState="work", cond=doswitch() )
				}	 
				state("work") { //this:State
					action { //it:State
						println("indoorparkingservicegui waiting for commands ...")
						updateResourceRep( "indoorparkingservicegui waiting for commands ..."  
						)
					}
					 transition(edgeName="t00",targetState="requestToenter",cond=whenDispatch("doAction"))
				}	 
				state("requestToenter") { //this:State
					action { //it:State
						println("indoorparkingservicegui requestToenter")
						updateResourceRep( "indoorparkingservicegui requestToenter"  
						)
						request("reqenter", "reqenter(bob)" ,"clientservice" )  
						stateTimer = TimerActor("timer_requestToenter", 
							scope, context!!, "local_tout_indoorparkingservicegui_requestToenter", 1000.toLong() )
					}
					 transition(edgeName="t01",targetState="retrylater",cond=whenTimeout("local_tout_indoorparkingservicegui_requestToenter"))   
					transition(edgeName="t02",targetState="enterthecar",cond=whenReply("enter"))
				}	 
				state("enterthecar") { //this:State
					action { //it:State
						if( checkMsgContent( Term.createTerm("enter(SLOTNUM)"), Term.createTerm("enter(SLOTNUM)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 SLOTNUM = payloadArg(0).toInt()  
								println("indoorparkingservicegui receives SLOTNUM = $SLOTNUM")
								updateResourceRep( "indoorparkingservicegui receives SLOTNUM = $SLOTNUM"  
								)
						}
					}
					 transition( edgeName="goto",targetState="retrylater", cond=doswitchGuarded({ SLOTNUM == 0  
					}) )
					transition( edgeName="goto",targetState="movethecartoindoor", cond=doswitchGuarded({! ( SLOTNUM == 0  
					) }) )
				}	 
				state("movethecartoindoor") { //this:State
					action { //it:State
						println("indoorparkingservicegui moving the car in the INDOOR and press CARENTER")
						updateResourceRep( "indoorparkingservicegui oving the car in the INDOOR and press CARENTER"  
						)
						request("carenter", "carenter($SLOTNUM)" ,"clientservice" )  
					}
					 transition(edgeName="t03",targetState="afterreceipt",cond=whenReply("receipt"))
				}	 
				state("afterreceipt") { //this:State
					action { //it:State
						println("indoorparkingservicegui leaves")
						updateResourceRep( "indoorparkingservicegui leaves"  
						)
					}
				}	 
				state("retrylater") { //this:State
					action { //it:State
						println("indoorparkingservicegui will retry later")
						updateResourceRep( "indoorparkingservicegui will retry later"  
						)
						forward("goToWork", "goToWork(bob)" ,"clientservice" ) 
					}
				}	 
			}
		}
}
