/* Generated by AN DISI Unibo */ 
package it.unibo.parkservicestatusgui

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Parkservicestatusgui ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("parkservicestatusgui STARTS")
						updateResourceRep( "parkservicestatusgui STARTS"  
						)
					}
					 transition( edgeName="goto",targetState="toggleState", cond=doswitch() )
				}	 
				state("toggleState") { //this:State
					action { //it:State
						println("parkservicestatusgui toggle state")
						updateResourceRep( "parkservicestatusgui toggle state"  
						)
						forward("toggleState", "toggleState(X)" ,"parkmanagerservice" ) 
						delay(1000) 
						println("parkservicestatusgui toggle state")
						updateResourceRep( "parkservicestatusgui toggle state"  
						)
						forward("toggleState", "toggleState(X)" ,"parkmanagerservice" ) 
					}
				}	 
			}
		}
}
