version: '3'
services:
  wenv:
    image: docker.io/natbodocker/virtualrobotdisi:2.0
    ports:
      - 8090:8090
      - 8091:8091
  basicrobot:
    image: docker.io/natbodocker/basicrobot21virtual:1.0
    ports:
      - 8020:8020/tcp
      - 8020:8020/udp
    depends_on:
      - wenv
  indoorarea:
    image: docker.io/sembravaqualcuno/automatedcarparking-indoorarea:1.0
    env_file:
      - variables.env
    stdin_open: true
    ports:
      - 8025:8025/udp
  outdoorarea:
    image: docker.io/sembravaqualcuno/automatedcarparking-outdoorarea:1.0
    env_file:
      - variables.env
    stdin_open: true
    ports:
      - 8026:8026/udp
  parkingarea:
    image: docker.io/sembravaqualcuno/automatedcarparking-parkingarea:1.0
    env_file:
      - variables.env
    stdin_open: true
    ports:
      - 8027:8027/udp
  parkmanagerservice:
    image: docker.io/sembravaqualcuno/automatedcarparking-parkmanagerservice:1.1
    env_file:
      - variables.env
    ports:
      - 8080:8080/tcp
      - 8080:8080/udp
    depends_on:
      - basicrobot
      - indoorarea
      - outdoorarea
      - parkingarea
