/* Generated by AN DISI Unibo */ 
package it.unibo.trolley

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Trolley ( name: String, scope: CoroutineScope  ) : ActorBasicFsm( name, scope ){

	override fun getInitialState() : String{
		return "s0"
	}
	@kotlinx.coroutines.ObsoleteCoroutinesApi
	@kotlinx.coroutines.ExperimentalCoroutinesApi			
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		
				val HOME : Pair<String,String> = Pair("0", "0")
				val INDOOR : Pair<String,String> = Pair("6", "0")
				val OUTDOOR : Pair<String,String> = Pair("6", "4")
				val SLOT1 : Pair<String,String> = Pair("1", "1")
				val SLOT2 : Pair<String,String> = Pair("1", "2")
				val SLOT3 : Pair<String,String> = Pair("1", "3")
				val SLOT4 : Pair<String,String> = Pair("4", "1")
				val SLOT5 : Pair<String,String> = Pair("4", "2")
				val SLOT6 : Pair<String,String> = Pair("4", "3")
				var currState : String = "INIT"
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						println("trolley STARTS")
						updateResourceRep( "trolley STARTS"  
						)
						itunibo.planner.plannerUtil.loadRoomMap( "parkingMap"  )
						itunibo.planner.plannerUtil.initAI(  )
						println("INITIAL MAP")
						itunibo.planner.plannerUtil.showMap(  )
						itunibo.planner.plannerUtil.startTimer(  )
					}
					 transition( edgeName="goto",targetState="idle", cond=doswitch() )
				}	 
				state("idle") { //this:State
					action { //it:State
						println("trolley IDLE")
						updateResourceRep( "trolley IDLE"  
						)
						 currState = "IDLE"  
						 if(!itunibo.planner.plannerUtil.atHome()){
										itunibo.planner.plannerUtil.planForGoal(HOME.first, HOME.second)
										var mv : String = itunibo.planner.plannerUtil.getNextPlannedMove()
										while(! mv.equals("")){
											when(mv){
												"w" ->
						request("step", "step(340)" ,"basicrobot" )  
						
													"s" ->
						forward("cmd", "cmd(s)" ,"basicrobot" ) 
						
													"l" ->
						forward("cmd", "cmd(l)" ,"basicrobot" ) 
						
													"r" ->
						forward("cmd", "cmd(r)" ,"basicrobot" ) 
						
													else -> {println("Command error")}
						 } //end when
												delay(340)
												itunibo.planner.plannerUtil.updateMap(mv)
												mv = itunibo.planner.plannerUtil.getNextPlannedMove()
						} 
						} 
						println("trolley at HOME")
						updateResourceRep( "trolley at HOME"  
						)
					}
					 transition(edgeName="t08",targetState="working",cond=whenDispatch("moveToInOutdoor"))
					transition(edgeName="t09",targetState="working",cond=whenDispatch("moveToPark"))
					transition(edgeName="t010",targetState="stopped",cond=whenDispatch("stop"))
					transition(edgeName="t011",targetState="idle",cond=whenDispatch("goToIdle"))
				}	 
				state("working") { //this:State
					action { //it:State
						println("$name in ${currentState.stateName} | $currentMsg")
						println("trolley WORKING")
						if( checkMsgContent( Term.createTerm("moveToInOutdoor(WHERE)"), Term.createTerm("moveToInOutdoor(WHERE)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 var WHERE = payloadArg(0)  
								if(  WHERE.equals("indoor")  
								 ){println("trolley trip to INDOOR start")
								updateResourceRep( "trolley trip to INDOOR start"  
								)
								 
													itunibo.planner.plannerUtil.planForGoal(INDOOR.first,INDOOR.second) 
													currState = "INDOOR"
								}
								if(  WHERE.equals("outdoor")  
								 ){println("trolley trip to OUTDOOR start")
								updateResourceRep( "trolley trip to OUTDOOR start"  
								)
								 
													itunibo.planner.plannerUtil.planForGoal(OUTDOOR.first,OUTDOOR.second) 
													currState = "OUTDOOR"
								}
								
												var mv : String = itunibo.planner.plannerUtil.getNextPlannedMove()
												while(! mv.equals("")){
													when(mv){
														"w" ->
								request("step", "step(340)" ,"basicrobot" )  
								
															"s" ->
								forward("cmd", "cmd(s)" ,"basicrobot" ) 
								
															"l" ->
								forward("cmd", "cmd(l)" ,"basicrobot" ) 
								
															"r" ->
								forward("cmd", "cmd(r)" ,"basicrobot" ) 
								
															else -> {println("Command error")}
								 } //end when
														delay(340)
														itunibo.planner.plannerUtil.updateMap(mv)
														mv = itunibo.planner.plannerUtil.getNextPlannedMove()
								} 
								if(  WHERE.equals("outdoor")  
								 ){println("trolley trip to OUTDOOR end")
								updateResourceRep( "trolley trip to OUTDOOR end"  
								)
								forward("goToIdle", "goToIdle(X)" ,"trolley" ) 
								}
								if(  WHERE.equals("indoor")  
								 ){println("trolley trip to INDOOR end")
								updateResourceRep( "trolley trip to INDOOR end"  
								)
								}
						}
						if( checkMsgContent( Term.createTerm("moveToPark(SLOTNUM)"), Term.createTerm("moveToPark(SLOTNUM)"), 
						                        currentMsg.msgContent()) ) { //set msgArgList
								 
												var SLOTNUM = payloadArg(0).toInt()
												if( currState.equals("INDOOR"))
													currState = "PARKIN"
												else
													currState = "PARKOUT"
								println("trolley moveToPark($SLOTNUM)")
								updateResourceRep( "trolley moveToPark($SLOTNUM)"  
								)
								
												when(SLOTNUM){
													1 -> itunibo.planner.plannerUtil.planForGoal(SLOT1.first, SLOT1.second)
													2 -> itunibo.planner.plannerUtil.planForGoal(SLOT2.first, SLOT2.second)
													3 -> itunibo.planner.plannerUtil.planForGoal(SLOT3.first, SLOT3.second)
													4 -> itunibo.planner.plannerUtil.planForGoal(SLOT4.first, SLOT4.second)
													5 -> itunibo.planner.plannerUtil.planForGoal(SLOT5.first, SLOT5.second)
													6 -> itunibo.planner.plannerUtil.planForGoal(SLOT6.first, SLOT6.second)
												}
												
												var mv = itunibo.planner.plannerUtil.getNextPlannedMove()
												while(! mv.equals("")){
													when(mv){
														"w" ->
								request("step", "step(340)" ,"basicrobot" )  
								
															"s" ->
								forward("cmd", "cmd(s)" ,"basicrobot" ) 
								
															"l" ->
								forward("cmd", "cmd(l)" ,"basicrobot" ) 
								
															"r" ->
								forward("cmd", "cmd(r)" ,"basicrobot" ) 
								
															else -> {println("Command error")}
								 } //end when
														delay(340)
														itunibo.planner.plannerUtil.updateMap(mv)
														mv = itunibo.planner.plannerUtil.getNextPlannedMove()
														
								} 
								updateResourceRep( "trolley trip to park slot $SLOTNUM end"  
								)
								println("trolley trip to park slot $SLOTNUM end")
								if(  currState.equals("PARKIN")  
								 ){forward("goToIdle", "goToIdle(X)" ,"trolley" ) 
								}
						}
					}
					 transition(edgeName="t012",targetState="working",cond=whenDispatch("moveToPark"))
					transition(edgeName="t013",targetState="working",cond=whenDispatch("moveToInOutdoor"))
					transition(edgeName="t014",targetState="idle",cond=whenDispatch("goToIdle"))
					transition(edgeName="t015",targetState="stopped",cond=whenDispatch("stop"))
				}	 
				state("stopped") { //this:State
					action { //it:State
						println("trolley STOPPED")
						updateResourceRep( "trolley STOPPED"  
						)
					}
					 transition(edgeName="t016",targetState="working",cond=whenDispatchGuarded("resume",{ currState.equals("INDOOR")  
					}))
					transition(edgeName="t017",targetState="working",cond=whenDispatchGuarded("resume",{ currState.equals("PARKOUT")  
					}))
					transition(edgeName="t018",targetState="idle",cond=whenDispatchGuarded("resume",{ currState.equals("PARKIN")  
					}))
					transition(edgeName="t019",targetState="idle",cond=whenDispatchGuarded("resume",{ currState.equals("OUTDOOR")  
					}))
					transition(edgeName="t020",targetState="idle",cond=whenDispatchGuarded("resume",{ currState.equals("IDLE")  
					}))
				}	 
			}
		}
}
